In [1]:
import numpy as np;

In [4]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T
x.shape, y.shape

((4, 2), (4, 1))

In [6]:
def sig(z):
    return 1/(1+np.exp(-z));

# With 0 hidden layers

In [13]:
weights = 2 * np.random.random((2,1)) -1
base = 2 * np.random.random(1) -1

weights, base

(array([[-0.81070782],
        [-0.26896578]]), array([-0.84225766]))

In [14]:
output0 = x
output = sig(np.dot(output0,weights) + base)
output

array([[ 0.30105951],
       [ 0.24764287],
       [ 0.16070856],
       [ 0.12764636]])

# With 1 hidden layer

In [15]:
wh = 2 * np.random.random((2,2)) - 1 # hidden weights
bh = 2 * np.random.random((1,2)) - 1 # hidden base


wo = 2 * np.random.random((2,1)) -1
bo = 2 * np.random.random(1) -1

In [16]:
output0 = x
output_hidden = sig(np.dot(output0,wh) + bh) # applying the hidden layer
output1 = sig(np.dot(output_hidden,wo) + bo) # final output
output1

array([[ 0.59384051],
       [ 0.63040108],
       [ 0.57375046],
       [ 0.60577361]])