In [1]:
import numpy as np

In [4]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,1,1,0]]).T

x.shape,y.shape

((4, 2), (4, 1))

In [5]:
def sig(z):
    return 1/ (1+np.exp(-z))

In [6]:
def derivativeSig(z):
    return sig(z) * (1-sig(z))

In [18]:
wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2)) - 1
lr = 0.1
wo = 2*np.random.random((2,1)) - 1
bo = 2*np.random.random((1)) - 1

wh,bh, wo, bo

(array([[-0.25022245,  0.42577003],
        [ 0.42884275, -0.88926434]]),
 array([[-0.2927278 ,  0.90218381]]),
 array([[ 0.90485214],
        [ 0.57790696]]),
 array([ 0.86005362]))

In [19]:
# Forward propagation
output0 = x

input_hidden = np.dot(output0,wh) + bh
output_hidden = sig(input_hidden)

input_final = np.dot(output_hidden,wo) + bo
output = sig(input_final)

output

array([[ 0.83994939],
       [ 0.83672277],
       [ 0.83881329],
       [ 0.83726693]])

In [20]:
# Code for backward propagation
for itr in range(99999):
        output0 = x

        input_hidden = np.dot(output0,wh) + bh
        output_hidden = sig(input_hidden)

        input_final = np.dot(output_hidden,wo) + bo
        output = sig(input_final)

        # there are three terms to be calculated to finally calculate dE/dwij
        first_term_output_layer = output - y # dE/dOj
        second_term_output_layer = derivativeSig(input_final) # dOj/d_input_j
        first_second_output_layer = first_term_output_layer * second_term_output_layer

        # first term of hidden layer depends on the first_second_output_layer * wij
        # thats how back propagation is done.
        # math used : total derivative
        # because dE/dOj depends on inp1 , .. inpk of next layer(in this case output layer)
        first_term_hidden_layer = np.dot(first_second_output_layer,wo.T)
        second_term_hidden_layer = derivativeSig(input_hidden) # dOj/d_input_j
        first_second_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

        # calculating slopes for wo and bo
        changes_output = np.dot(output_hidden.T,first_second_output_layer)
        changes_output_bias = np.sum(first_second_output_layer,axis = 0, keepdims = True)

        # calculating slopes for wh and bh 
        changes_hidden = np.dot(output0.T,first_second_hidden_layer)
        changes_hidden_bias = np.sum(first_second_hidden_layer,axis = 0, keepdims = True)

        # update weights and biases
        wo = wo - lr * changes_output
        bo = bo - lr * changes_output_bias
        wh = wh - lr * changes_hidden
        bh = bh - lr * changes_hidden_bias

output, wh,bh, wo, bo

(array([[ 0.0182782 ],
        [ 0.97934042],
        [ 0.97870526],
        [ 0.01719464]]), array([[-6.26618672,  8.72777202],
        [ 6.6159473 , -9.30741089]]), array([[ 3.11047788,  5.02134073]]), array([[-8.58335333],
        [-8.37669413]]), array([[ 12.55523935]]))