# Covers Forward Propagation + (backward propagation for neural network with no hidden layers )

In [57]:
import numpy as np

In [58]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T

x.shape,y.shape

((4, 2), (4, 1))

In [59]:
def sig(z):
    return 1/(1+np.exp(-z))

In [60]:
def derivativeSig(z):
    return sig(z) * (1-sig(z))

In [71]:
weights = 2 * np.random.random((2,1)) - 1
base = 2 * np.random.random((1)) - 1
lr = 0.01
weights,base

(array([[ 0.46848316],
        [-0.73636653]]), array([-0.98717058]))

In [62]:
# With no hidden layer
# Propagating forward
output0 = x
output = sig(np.dot(output0,weights) + base)
output

array([[ 0.71108068],
       [ 0.61686196],
       [ 0.51981809],
       [ 0.41457733]])

In [73]:
# Propagating backward
# dE/dWij has three terms to be multiplied

# dE/dOj
for itr in range(10000):
        output = sig(np.dot(x,weights) + base)
        
        first_term = output - y # shape 4,1

        # for dOj/d_input_j
        input_j = np.dot(output0,weights) + base
        second_term = derivativeSig(input_j) # shape 4,1

        # multiply first and second
        result1 = first_term * second_term

        # for d_input_j/dWij = Oi, Oi for each weight should be calculated separately
        changes = np.zeros((2,1))
        # print changes for clarity

        for i in range (2):
            for j in range (4):
                changes [i][0] += result1[j][0] * output0[j][i]

        # changes represent slope for weights
        weights = weights - lr * changes
        changes = 0.0
        # for base, only one base therefore, no need of i loop
        for j in range (4):
                changes += result1[j][0] * 1

        base = base - lr * changes
        
output = sig(np.dot(x,weights) + base)
weights, base, output

(array([[ 3.50355885],
        [ 3.50341934]]), array([-5.36399231]), array([[ 0.00466036],
        [ 0.13463628],
        [ 0.13465254],
        [ 0.83794082]]))

In [74]:
# Propagating backward
# dE/dWij has three terms to be multiplied

# dE/dOj
for itr in range(10000):
        output = sig(np.dot(x,weights) + base)
        
        first_term = output - y # shape 4,1

        # for dOj/d_input_j
        input_j = np.dot(output0,weights) + base
        second_term = derivativeSig(input_j) # shape 4,1

        # multiply first and second
        result1 = first_term * second_term

        # for d_input_j/dWij = Oi, Oi for each weight should be calculated separately
        changes = np.zeros((2,1))
        # print changes for clarity

        changes = np.dot(output0.T,result1)

        # changes represent slope for weights
        weights = weights - lr * changes
        changes = 0.0
        # for base, only one base therefore, no need of i loop
        changes = np.sum(result1)

        base = base - lr * changes
        
output = sig(np.dot(x,weights) + base)
weights, base, output

(array([[ 4.01521403],
        [ 4.01519665]]), array([-6.1255105]), array([[ 0.0021816 ],
        [ 0.1080984 ],
        [ 0.10810008],
        [ 0.87044513]]))